config/routes.rb
Snackoverload::Application.routes.draw do


  root to: 'questions#index'
  resources :favorite_tags, only: [:index, :create, :destroy]
  devise_for :users
  resources :users, only: [:index, :show]
  resources :questions do
    resources :answers, only:[:create]
  end
  resources :tags, only: [:index, :show]
  resources :answers, only: [:create]
  resources :comments, only: [:create, :destroy]
  get 'about', to: 'StaticPages#about'
  put 'votes', to: 'votes#update'
  get 'guest', to: 'Users#guest_log_in'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Commentable
  include Votable
  attr_accessible :answerer_id, :body, :question_id
  belongs_to :question
  belongs_to :answerer, foreign_key: :answerer_id, class_name: 'User'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commentable_id, :commentable_type, :commenter_id
  validates :body, :commentable_id, :commentable_type, :commenter_id, presence: true
  
  belongs_to :commentable, polymorphic: true
  belongs_to :commenter, foreign_key: :commenter_id, class_name: 'User'
  
  def as_json(*args)
    hash = super(*args)
    hash.merge!({
      "commenter_email" => self.commenter_email
    })
  end
  
  def commenter_email
    self.commenter.email
  end
  
end

app/models/commentable.rb
module Commentable
  extend ActiveSupport::Concern
  
  included do
    has_many :comments, as: :commentable
  end
  
end

app/models/favorite_tag.rb
class FavoriteTag < ActiveRecord::Base
  attr_accessible :tag_id, :user_id
  validates :tag_id, :user_id, :presence => true
  validates :tag_id, :uniqueness => {scope: :user_id}
  
  belongs_to :user
  belongs_to :tag
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Commentable
  include Votable
  attr_accessible :asker_id, :body, :title
  validates :asker_id, :body, :title, presence: true
  
  has_many :answers
  has_many :question_taggings
  has_many :tags, through: :question_taggings, source: :tag
  
  belongs_to :asker, foreign_key: :asker_id, class_name: 'User'
  
  def as_json(*args)
    hash = super(*args)
    hash.merge!({
      "confirmed" => confirmed?,
      "answered" => answered?,
      "score" => score,
    })
  end
  
  def confirmed?
    self.answers.where(chosen: true).count > 0 
  end
  
  def answered?
    self.answers.count > 0
  end
end

app/models/question_tagging.rb
class QuestionTagging < ActiveRecord::Base
  attr_accessible :question_id, :tag_id
  belongs_to :question
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :question_taggings
  has_many :tagged_questions, through: :question_taggings, source: :question
  has_many :favorite_tags
  has_many :favoriting_users, through: :favorite_tags, source: :user
  
  def as_json(*args)
    hash = super(*args)
    hash.merge!({
      "favoriters_count" => favoriting_users.count,
      "tagged_questions_count" => tagged_questions.count
    })
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :questions, foreign_key: :asker_id
  has_many :answered_questions, foreign_key: :answerer_id, class_name: 'Answer'
  has_many :favorite_tags
  has_many :tags, through: :favorite_tags, source: :tag
  
  def gravatar_url
      gravatar_id = Digest::MD5::hexdigest(self.email).downcase
      "http://gravatar.com/avatar/#{gravatar_id}.png?d=identicon"
  end
  
  def rep
    (rand * 1000000).ceil
  end
  
  def as_json(*args)
    hash = super(*args)
    hash.merge!({
      "gravatar_url" => gravatar_url,
      "rep" => rep
    })
  end
  
end

app/models/votable.rb
module Votable
  extend ActiveSupport::Concern
  
  included do
    has_many :votes, as: :votable
  end

  #score
  def score
    self.votes.sum('value')
  end
  
  def upvotes
    self.votes.where('value = 1').count
  end
  
  def downvotes
    self.votes.where('value = -1').count
  end
  
  def vote_for_user(user)
    if(user)
      my_vote = self.votes.find_by_voter_id(user.id)
      return my_vote.value if my_vote
    end

    0
  end
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :value, :votable_id, :votable_type, :voter_id
  validates :votable_id, uniqueness: {scope: :voter_id}
  belongs_to :votable, polymorphic: true
  
  
  def self.get_old_vote(user_id, votable_type, votable_id)
    vote = self.find_by_voter_id_and_votable_type_and_votable_id(
    user_id,
    votable_type,
    votable_id)
    vote
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  def index
    @questions = Question.includes(:tags, :votes, :asker, :answers, :comments)
    @users = User.all
    respond_to do |format|
      format.html
      format.json do
        render json: @questions, include: [ 
          :tags, 
          :votes, 
          :asker, 
          { :answers => { :include => [{ :comments => { :methods => [:commenter_email] }}, :answerer]}},
          { :comments => { :methods => [:commenter_email] }}
        ]
      end
    end
  end
  
  def new
    @question = Question.new
    @tags = Tag.all
  end
  
  def create

    @question = Question.new(params[:question])
    @question.tag_ids = params[:tags]
    @question.asker_id = current_user.id
    
    if (params[:new_tags_string])
      new_tags = params[:new_tags_string].split(', ')
      new_tags.each do |tag|
        @question.tags << Tag.new(name: tag)
      end
    end
    if @question.save
      redirect_to questions_url
    else
      @tags = Tag.all
      flash.now[:errors] = @question.errors.full_messages
      render :new
    end
  end
  
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    if(params[:type])
      if(params[:type] == 'favorite')
        @tags = current_user ? current_user.tags : Tag.includes(:favoriting_users, :tagged_questions)
      elsif(params[:type] == 'all')
        @tags = Tag.includes(:favoriting_users, :tagged_questions)
      end
    else
      @tags = Tag.includes(:favoriting_users, :tagged_questions) 
    end
    
    @COLCOUNT = 3
    respond_to do |format|
      format.html
      format.json {render json: @tags}
    end
  end

  def show
    @tag = Tag.find(params[:id])
    @questions = @tag.tagged_questions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @rep = random_rep
  end
  
  def index
    @COLCOUNT = 2
    @users = User.all
    
    respond_to do |format|
      format.html
      format.json {render json: @users}
    end
    
  end
  
  def guest_log_in
    if user_signed_in?
      sign_out(current_user)
    end
    
    create_guest_user
    redirect_to root_url
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def update
    new_vote_value = params[:vote][:value].to_i
    @vote = Vote.get_old_vote(
      current_user.id, 
      params[:vote]['votable_type'],
      params[:vote]['votable_id'])
      
    if(@vote)
      if(@vote.value == new_vote_value)
        @vote.value = 0
      else
        @vote.value = new_vote_value
      end
    else
      @vote = Vote.new(params[:vote])
      @vote.voter_id = current_user.id
    end
    
    if @vote.save
      votable_type = @vote.votable_type.constantize
      votable_instance = votable_type.find(@vote.votable_id)
      new_score = votable_instance.score
      render json: {score: new_score, new_vote: @vote.value}
    else
      render json: @vote.errors.full_messages
    end
    
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  def random_rep
    (rand * 1000000).ceil
  end
   
   def create_guest_user
     u = User.create(:email => "foodie_#{rand(999999)}@eat.mmm")
     u.save(:validate => false)
     sign_in(u)
     u
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorite_tags_helper.rb
module FavoriteTagsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/questions/index.html.erb
<div class="col-xs-9" id="main">
  <!-- <%= render 'shared/questions_list', questions: @questions%> -->
</div>
<div class="col-xs-3" id="sidebar">
  <!-- <%= render 'shared/sidebar'%> -->
</div>

<!-- all backbone now baby -->


<script>

  <% if current_user %>
    Snackoverload.currentUserId = <%=current_user.id%>
  <% end %>
  
  Snackoverload.users = <%= @users.to_json.html_safe %>;
  $(document).ready(function(){
    Snackoverload.initialize();
  });
</script

app/views/questions/new.html.erb
<div class="col-xs-9">
<form action="<%=questions_url%>" method="post" accept-charset="utf-8" role="form">
  <input 
   type="hidden" 
   name="authenticity_token" 
   value="<%=form_authenticity_token%>" 
   id="authenticity_token"
  >
  
  <div class="form-group">
  <label for="title">Title</label>
  <input class="form-control" type="text" name="question[title]" value="<%=@question.title%>" id="title">
  <br>
</div>

  <div class="form-group">
    
  <label for="question">Question</label>
  <textarea class="form-control" type="text" name="question[body]" id="question"><%=@question.body%></textarea>
</div>
  <br>
  
  <label for="tags">Tags</label>
  <br>
  <select multiple class="chosen-select" name='tags[]' id="tags">
    <%@tags.each do |tag|%>
      <option value="<%=tag.id%>"><%=tag.name%></option>
    <%end%>
  </select>
  <br>
  <br>
  <button id="add-tag-button" class='btn btn-primary'>Add Additional Tags</button>
  <br>
  <br>
  <div class='new-tag-zone'></div>
  <br>
  <button type="submit" class="btn btn-primary">Ask Question</button>
</form>
</div>

<script>
  $('.chosen-select').chosen();
  $('#add-tag-button').on('click', function(event){
    event.preventDefault();
    var ntz = $('.new-tag-zone');
    if(ntz.html() == ""){
      ntz.append('<div class="form group" <label>New tags, separated by commas.</label>')
      ntz.append('<input type="text" class="form-control" name="new_tags_string"></div><br><br>')
    }
    
  });
</script>

app/views/questions/show.html.erb
<!-- title
question body
comments

# answers
answer
comments -->

<div class="question row">
  <div class="page-header">
    <h1><%=@question.title%></h1>
  </div>  
  <div class="col-xs-1">
    <%=render "shared/vote_block", votable: @question%>
  </div>
  <div class="col-xs-11">
    <div class="question-content">  

    
      <p class="lead"><%=@question.body%></p>
      <%=render 'shared/tags', tags: @question.tags%>
      <p>Asked by: <%=render 'shared/user', user: @question.asker%> 
        at <%=render 'shared/timestamp', time: @question.created_at%></p>
    </div> <!-- question content -->
    <%=render 'shared/comments', commentable: @question%>
  </div><!-- question -->
  <hr>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-11">
      <h2><%=@question.answers.count%> answers</h2>

      <ul>
        <%@question.answers.each do |answer|%>
        <li>
          <div class="answer">
            <p class="lead"><%=answer.body%></p>
            <p>
              answered by: <%=render 'shared/user', user: answer.answerer%>
              at <%=render 'shared/timestamp', time: answer.created_at%>
            </p>
            <%=render 'shared/comments', commentable: answer%>
          </div>
        </li>
        <%end%>
      </ul>
    </div>

    <hr>
    <h2>Have the Answer?</h2>
    <%if user_signed_in?%>
    <%=render 'shared/answer_form', question: @question%>
    <%else%>
    <h3><a href="<%=new_user_session_url%>">log in, and post it!</a></h3>
    <%end%>
  </div>
</div>

<%if current_user%>
<script>
$('.comment-form').on('submit', function(event){
  event.preventDefault();
  $.ajax({
    type: "POST",
    url: "<%=comments_url%>",
    data: $(event.target).serializeJSON(),
    success: function(comment){
      var selectorString = '[data-commentable="' + 
      comment.commentable_type +
      '_' +
      comment.commentable_id + 
      '"]';
                              
      var $commentList = $(selectorString);
      var newCommentStr = '<li>' + 
      comment.body +  
      ' - ' + 
      '<a href="<%=user_url(current_user)%>">' + 
      '<%=current_user.email%></a>' + 
      '</li>';
      $commentList.append(newCommentStr)
        

    }
  })
})

$('.vote').on('click', function(event){
  var upButton = $('.vote.up')
  var downButton = $('.vote.down')
  var up = $(event.currentTarget).data('type') === "upvote";
  var votableString = $(event.currentTarget).data('votable');
  var votableType = votableString.split('_')[0];
  var votableID = parseInt(votableString.split('_')[1]);
  var votesURL = "<%=votes_url%>";
  var newVote = {vote: {
    votable_type: votableType,
    votable_id: votableID,
    value: up ? 1 : -1
  }};
  
  console.log(newVote);
  $.ajax({
    type: "PUT",
    url: votesURL,
    data: newVote,
    success: function(score){
      if(score['new_vote'] == 1){
        upButton.addClass('lit');
        downButton.removeClass('lit');
      }
      else if(score['new_vote'] == -1){
        upButton.removeClass('lit');
        downButton.addClass('lit');
      }
      else{
        //vote is 0
        upButton.removeClass('lit');
        downButton.removeClass('lit');
      }
      //if vote val is 0, toggle the button
      //if it is 1 turn on the top
      //if it is -1 turn on the bottom
      $('.score[data-votable="' + votableString +'"]').html(score['score']);
      
    }
  })
})
</script
<%end%>