config/routes.rb
Snackoverload::Application.routes.draw do


  root to: 'questions#index'
  resources :favorite_tags, only: [:index, :create, :destroy]
  devise_for :users
  resources :users, only: [:index, :show]
  resources :questions do
    resources :answers, only:[:create]
  end
  resources :tags, only: [:index, :show]
  resources :answers, only: [:create]
  resources :comments, only: [:create, :destroy]
  get 'about', to: 'StaticPages#about'
  put 'votes', to: 'votes#update'
  get 'guest', to: 'Users#guest_log_in'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Commentable
  include Votable
  attr_accessible :answerer_id, :body, :question_id
  belongs_to :question
  belongs_to :answerer, foreign_key: :answerer_id, class_name: 'User'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commentable_id, :commentable_type, :commenter_id
  validates :body, :commentable_id, :commentable_type, :commenter_id, presence: true
  
  belongs_to :commentable, polymorphic: true
  belongs_to :commenter, foreign_key: :commenter_id, class_name: 'User'
  
  def as_json(*args)
    hash = super(*args)
    hash.merge!({
      "commenter_email" => self.commenter_email
    })
  end
  
  def commenter_email
    self.commenter.email
  end
  
end

app/models/commentable.rb
module Commentable
  extend ActiveSupport::Concern
  
  included do
    has_many :comments, as: :commentable
  end
  
end

app/models/favorite_tag.rb
class FavoriteTag < ActiveRecord::Base
  attr_accessible :tag_id, :user_id
  validates :tag_id, :user_id, :presence => true
  validates :tag_id, :uniqueness => {scope: :user_id}
  
  belongs_to :user
  belongs_to :tag
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Commentable
  include Votable
  attr_accessible :asker_id, :body, :title
  validates :asker_id, :body, :title, presence: true
  
  has_many :answers
  has_many :question_taggings
  has_many :tags, through: :question_taggings, source: :tag
  
  belongs_to :asker, foreign_key: :asker_id, class_name: 'User'
  
  def as_json(*args)
    hash = super(*args)
    hash.merge!({
      "confirmed" => confirmed?,
      "answered" => answered?,
      "score" => score,
    })
  end
  
  def confirmed?
    self.answers.where(chosen: true).count > 0 
  end
  
  def answered?
    self.answers.count > 0
  end
end

app/models/question_tagging.rb
class QuestionTagging < ActiveRecord::Base
  attr_accessible :question_id, :tag_id
  belongs_to :question
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :question_taggings
  has_many :tagged_questions, through: :question_taggings, source: :question
  has_many :favorite_tags
  has_many :favoriting_users, through: :favorite_tags, source: :user
  
  def as_json(*args)
    hash = super(*args)
    hash.merge!({
      "favoriters_count" => favoriting_users.count,
      "tagged_questions_count" => tagged_questions.count
    })
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :questions, foreign_key: :asker_id
  has_many :answered_questions, foreign_key: :answerer_id, class_name: 'Answer'
  has_many :favorite_tags
  has_many :tags, through: :favorite_tags, source: :tag
  
  def gravatar_url
      gravatar_id = Digest::MD5::hexdigest(self.email).downcase
      "http://gravatar.com/avatar/#{gravatar_id}.png?d=identicon"
  end
  
  def rep
    (rand * 1000000).ceil
  end
  
  def as_json(*args)
    hash = super(*args)
    hash.merge!({
      "gravatar_url" => gravatar_url,
      "rep" => rep
    })
  end
  
end

app/models/votable.rb
module Votable
  extend ActiveSupport::Concern
  
  included do
    has_many :votes, as: :votable
  end

  #score
  def score
    self.votes.sum('value')
  end
  
  def upvotes
    self.votes.where('value = 1').count
  end
  
  def downvotes
    self.votes.where('value = -1').count
  end
  
  def vote_for_user(user)
    if(user)
      my_vote = self.votes.find_by_voter_id(user.id)
      return my_vote.value if my_vote
    end

    0
  end
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :value, :votable_id, :votable_type, :voter_id
  validates :votable_id, uniqueness: {scope: :voter_id}
  belongs_to :votable, polymorphic: true
  
  
  def self.get_old_vote(user_id, votable_type, votable_id)
    vote = self.find_by_voter_id_and_votable_type_and_votable_id(
    user_id,
    votable_type,
    votable_id)
    vote
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    if(params[:type])
      if(params[:type] == 'favorite')
        @tags = current_user ? current_user.tags : Tag.includes(:favoriting_users, :tagged_questions)
      elsif(params[:type] == 'all')
        @tags = Tag.includes(:favoriting_users, :tagged_questions)
      end
    else
      @tags = Tag.includes(:favoriting_users, :tagged_questions) 
    end
    
    @COLCOUNT = 3
    respond_to do |format|
      format.html
      format.json {render json: @tags}
    end
  end

  def show
    @tag = Tag.find(params[:id])
    @questions = @tag.tagged_questions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @rep = random_rep
  end
  
  def index
    @COLCOUNT = 2
    @users = User.all
    
    respond_to do |format|
      format.html
      format.json {render json: @users}
    end
    
  end
  
  def guest_log_in
    if user_signed_in?
      sign_out(current_user)
    end
    
    create_guest_user
    redirect_to root_url
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  def random_rep
    (rand * 1000000).ceil
  end
   
   def create_guest_user
     u = User.create(:email => "foodie_#{rand(999999)}@eat.mmm")
     u.save(:validate => false)
     sign_in(u)
     u
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>snackoverload</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>

  <%= render 'shared/header'%>
    
  <div class="main">
    <div class="container"> 
      <div class="row">

          <%if notice%>
          <p class="notice"><%= notice %></p>
          <%end%>
            <%if alert%>
            <p class="alert"><%= alert %></p>
            <%end%>
              <%if flash[:errors]%>

              <%flash[:errors].each do |error|%>
              <li><%=error%></li>
              <%end%>

              <%end%>
              <%= yield %>
            </div>


        </div>
      </div>
    </body>
    </html>

app/views/shared/_answer_form.html.erb
<form action="<%=question_answers_url(question)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <textarea placeholder="answer here" name="answer[body]"></textarea>
  <br>
  <button id="answer-button" >Submit Answer</button>
</form>

app/views/shared/_comments.html.erb
<div class="comments">  
  <ul class='comments-list' 
   data-commentable="<%=commentable.class.to_s%>_<%=commentable.id%>" 
   >
    <%commentable.comments.each do |comment|%>
      <li><p><%=comment.body%> - <%=render 'shared/user', user: comment.commenter%> at <%=render 'shared/timestamp', time: comment.created_at%></p></li>
    <%end%>
  </ul>
  
  
  <form class="comment-form" accept-charset="utf-8">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="hidden" 
     name="comment[commentable_id]" value="<%=commentable.id%>">
    <input type="hidden" 
     name="comment[commentable_type]" value="<%=commentable.class.to_s%>">
     
    <label for="comment">Comment</label>
    <input type="text" name="comment[body]" id="comment" 
     placeholder="useful comment goes here">
     <input type="submit" value="Add Comment" id="comment-button">
  </form>
  
</div>

app/views/shared/_favorite_tags.html.erb
<h4>
  Favorite Tags
</h4>
<hr>
<% tags.each do |tag|%>
  <%=render 'shared/simple_tag', tag: tag%>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="navbar-header left-space">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/#"><%= image_tag 'brand.png', size: "150x36", class:"logo"%></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%=new_question_url%>">Ask Question</a></li>
        <li><a href="/#tags">Tags</a></li>
        <li><a href="/#users">Users</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/#about">About</a></li>
        
        <% if user_signed_in? %>
          <li class="dropdown">
            <a 
              href="#"  
              class="dropdown-toggle" 
              data-toggle="dropdown"><%=current_user.email%> 
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/#users/<%=current_user.id%>">My Profile</a></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_url, :method => :delete %></li>
            
            </ul>
          </li>
        <%else%>
          <li><a href="<%=new_user_registration_url%>">Sign Up</a></li>
          <li><a href="<%=new_user_session_url%>">Log In</a></li>
        <%end%>
        
      </ul>
    </div><!-- /.nav-collapse -->
</div><!-- /.navbar -->

app/views/shared/_no_favorites.html.erb
<h4>
  Favorite Tags
</h4>
<hr>
<p>Would go here if you had some.</p>
<p>Hover over a tag and check the box to favorite the tag.</p>

app/views/shared/_questions_list.html.erb
<%questions.each do |question|%>

<div class='row'>
  <div class="col-xs-2">
    <div class="question-stats">
      <div class="right-point"></div>
      <div class="question-vote-count"
       ><span class='stat-number'><%=question.score%></span><br>votes</div>
      <div 
       class="question-vote-answer <%= question.confirmed? ? "confirmed" : ""%> 
        <%= question.answered? ? "answered" : ""%>"
       ><span class='stat-number'><%=question.answers.count%></span><br>answers
      </div>
  </div>
  </div>

  <div class="question col-xs-10">
    <h2><a href="<%= question_url(question) %>"><%=question.title%></a></h2>
    <p><%=question.body%></p>
    <%=render 'shared/tags', tags: question.tags%>
    <p>Asked by: <%=render 'shared/user', user: question.asker%> 
       at <%=render 'shared/timestamp', time: question.created_at%></p>
</div>
  
</div>
<hr>
<%end%>

app/views/shared/_sidebar.html.erb
<% if user_signed_in?%>
  <%tags = current_user.tags%>
  <% if tags.count == 0 %>
    <%=render 'shared/no_favorites'%>
  <% else %>
  <%=render 'shared/favorite_tags', tags: tags%>
  <% end %>
<% else %>
<%=render 'shared/welcome_sidebar'%>
<% end %>

app/views/shared/_simple_tag.html.erb
<a class="tag" href="<%=tag_url(tag)%>"><%=tag.name%></a>

app/views/shared/_tag.html.erb
<%checked = " checked" if current_user && current_user.tags.find_by_id(tag.id)%>
<a class="tag" 
 href="<%=tag_url(tag)%>" 
 rel="popover"
 data-content='<input data-id="<%=tag.id%>" type="checkbox" <%=checked%> class="tag-popover-fave"><label>favorite</label>'
 
 ><%=tag.name%></a>

app/views/shared/_tags.html.erb
<%unless tags.empty?%>
<%tag_string = "Tags: "%>
  <%tag_links = tags.map{|tag| render 'shared/tag', tag: tag}%>
  <%tag_string = "Tags: " + tag_links.join(', ')%>
<%end%>

<p class="tags"><%=(tag_string || "").html_safe%></p>

app/views/shared/_timestamp.erb
<%=time.strftime("%l:%M %p-%m/%d/%Y")%>

app/views/shared/_user.html.erb
<a href="<%=user_url(user)%>"><%=user.email%></a>

app/views/shared/_vote_block.html.erb
<div class="vote-block"
  data-votable="<%=votable.class.to_s%>_<%=votable.id%>">
  
  <% my_vote = votable.vote_for_user(current_user) %>
 
  <div class="vote up <%=my_vote == 1 ? "lit" : ""%>" data-type="upvote" data-votable="<%=votable.class.to_s%>_<%=votable.id%>">
    
  </div>
  
  <div class="score" data-votable="<%=votable.class.to_s%>_<%=votable.id%>">
    <%=votable.score%>
  </div>
  
  <div class="vote down <%=my_vote == -1 ? "lit" : ""%>" data-type="downvote" data-votable="<%=votable.class.to_s%>_<%=votable.id%>">
  </div>
</div>

app/views/shared/_welcome_sidebar.html.erb
<h4>
  Hey! Look here!
  <hr>
</h4>
<div>
  <h5>Who are you?</h5>
  <p><a href="http://www.linkedin.com/in/jfiddler">Hi.</a></p>
</div>
<div>
  <h5>What is this?</h5>
  <p><a href="<%=about_url%>">This is what this is.</a></p>
</div>

<div>
  <h5>I don't want to sign up.</h5>
  <p><a href="<%=guest_url%>">Who would?</a></p>
</div>
<div>
  <h5>I do want to sign up.</h5>
  <p><a href="<%=new_user_registration_url%>">If you insist.</a></p>
</div>

<div>
  <h5>Index all the things!</h5>
  <p><a href="<%=users_url%>">Users</a>, 
     <a href="<%=tags_url%>">Tags</a>, 
     <a href="<%=questions_url%>">Questions</a>
   </p>
</div>